### ISSUE TITLE
Can't unlink a previous Org connection if I no longer have access to org

### ISSUE THREAD

**Issue by corysimmons** [amondnet/now-deployment#15]
1. Join org
2. Create Now "Git Integration" with it
3. Leave org
4. Can never get rid of the "Git Integration" in Now. If I click the "To disconnect, go to the app settings on GitHub." link to disconnect it, it 404's. Just have to suffer with seeing red `x` to signify build failure next to literally every repo I ever make unless I remove Now integration completely.

![image](https://user-images.githubusercontent.com/224636/71527995-c3ef9b00-28ab-11ea-8971-14c5ff85268d.png)

Going through and removing every association to Zeit and my Github now.

**Comment by amondnet** [comment]
@corysimmons Hi, the problem doesn't seem to be related to this project. Leaving an issue in [zeit now](https://github.com/zeit/now) will help you.

**Comment by corysimmons** [comment]
Okay thanks sorry
