### ISSUE TITLE
Feature: Ability to specify path for --local-config flag

### ISSUE THREAD

**Issue by iPwnPancakes** [amondnet/now-deployment#16]
I am currently set up with Travis CI and in my `travis.yml` I use the `--local-config` flag to use different now.json files depending on the environment I'm pushing to (e.g. Development, Staging, Production).

**Comment by amondnet** [comment]
@iPwnPancakes  Hi, the problem doesn't seem to be related to this project. Leaving an issue in zeit now will help you.
