### ISSUE TITLE
team_id seems to be not working

### ISSUE THREAD

**Issue by sergeyfilimonov** [amondnet/now-deployment#19]
Specifying team_id under `zeit-team-id` has no effect. Unless I indicate `scope` in `now.json` it's not choosing the right team. So I tried to remove `zeit-team-id` from my `deploy.yaml` and it still deploys well under the right scope. I would suggest to remove the requirement of `zeit-team-id` and recommend using only `now.json` to set a `scope`.

**Comment by amondnet** [comment]
https://github.com/amondnet/now-deployment/blob/c334a921c000b578c710d3d83ca696a37a1488bb/index.js#L21

`zeit-team-id` is required for comment( [find deployment](https://zeit.co/docs/api#endpoints/deployments/list-deployments) ), not deployment. The deployment will work normally without the `zeit-team-id`.

I will find a better way or make the comment optional.

**Comment by amondnet** [comment]
#20
