### ISSUE TITLE
Deploy stalled

### ISSUE THREAD

**Issue by devotox** [amondnet/now-deployment#23]
```
Now CLI 17.0.3
> [debug] [2020-02-14T01:02:32.103Z] user supplied a possible target for deployment

> [debug] [2020-02-14T01:02:32.103Z] user supplied a possible target for deployment
> [debug] [2020-02-14T01:02:32.111Z] GET https://api.zeit.co/www/user 

> [debug] [2020-02-14T01:02:32.111Z] GET https://api.zeit.co/www/user 
> [debug] [2020-02-14T01:02:32.661Z] GET https://api.zeit.co/www/user : 548.921ms

> [debug] [2020-02-14T01:02:32.661Z] GET https://api.zeit.co/www/user : 548.921ms
? Set up and deploy “~/work/zenunu/zenunu”? [Y/n] 
? Set up and deploy “~/work/zenunu/zenunu”? [Y/n] 
```

**Comment by shallwefootball** [comment]
i think add `--confirm` options in now cli

**Comment by sudkumar** [comment]
Yes. [Now CLI v17](https://github.com/zeit/now/releases/tag/now%4017.0.0) has this breaking change regarding the way Zeit project are linked to a repository. 

Please See
- https://zeit.co/docs/now-cli#commands/now/unique-options/name 
- https://zeit.co/docs/now-cli#commands/now/project-linking

I wish there was an env like `CI: true` that we can accept which will disable any interactivity with the now cli or we can have a way to specify the now cli version.

```diff
  with:
    now-args: "--prod"
+ env:
+   CI: true
```

cc @amondnet

**Comment by devotox** [comment]
--confirm works
