### ISSUE TITLE
Add instruction on getting `project_id` and `org_id`

### ISSUE THREAD

**Issue by jackguoAtJogg** [amondnet/now-deployment#27]
I think if you guys can add instruction on getting `now-project-id` and `now-org-id`. I was confused on how to get those two things and couldn't find in the now cli doc.

**Comment by amondnet** [comment]
@jackguoAtJogg I added that to the [README](https://github.com/amondnet/now-deployment/blob/docs/how-to-get/README.md). See [Project Linking](https://github.com/amondnet/now-deployment/blob/docs/how-to-get/README.md#project-linking)

**Comment by jackguoAtJogg** [comment]
@amondnet Thank you! I appreciated, I have one more question: does the `org_id` change based on different user from the organization?
