### ISSUE TITLE
undefined url on pull request comment

### ISSUE THREAD

**Issue by KevinBacas** [amondnet/now-deployment#37]
Hello, I'm having trouble setting up this action to deploy a PR and comment the URL.
Here is my configuration:
![image](https://user-images.githubusercontent.com/1434393/77170321-29be7e00-6abb-11ea-93e6-081288a36988.png)

Here is the comment I get on my PR:
![image](https://user-images.githubusercontent.com/1434393/77170407-4bb80080-6abb-11ea-8a56-32743c876c99.png)

If I look at the logs of the actions it seems like everything runs fine:
![image](https://user-images.githubusercontent.com/1434393/77170600-89b52480-6abb-11ea-9946-a287af7b2ddf.png)

https://github.com/Augora/Augora/runs/522025481?check_suite_focus=true#step:5:22

Am I missing something?

Thank you for your help 😃

**Comment by amondnet** [comment]
@KevinBacas Hi, if your deployment is made on team project, you should set `zeit-team-id`.  
related issue : https://github.com/amondnet/now-deployment/issues/19
related api: https://zeit.co/docs/api#endpoints/deployments/list-deployments

**Comment by KevinBacas** [comment]
It works! thank you for your help!
Great job on this action BTW, it will help me a lot 😄
