### ISSUE TITLE
Error: spawn /usr/local/bin/npx ENOENT

### ISSUE THREAD

**Issue by shaodahong** [amondnet/now-deployment#47]
https://github.com/shaodahong/ant-design/runs/652327012?check_suite_focus=true

**Comment by shaodahong** [comment]
In my see, variable set correctly, but not found `npx`?

**Comment by amondnet** [comment]
@shaodahong There was a mistake in the release process. Please try again.

**Comment by shaodahong** [comment]
Still have https://github.com/shaodahong/ant-design/runs/655136215?check_suite_focus=true

**Comment by amondnet** [comment]
@shaodahong 
Hi, the update seems to be applied after a certain period of time. I'm sorry, can you try again?

I tested it on my project and it all worked.
https://github.com/amondnet/now-deployment-example/runs/656048240?check_suite_focus=true

**Comment by shaodahong** [comment]
look like good, I will self-check, thank you.

https://github.com/shaodahong/now-deployment-example
