### ISSUE TITLE
Github comment link contains double https at the beginning

### ISSUE THREAD

**Issue by sobstel** [amondnet/now-deployment#51]
The link included in github comment link has a double "https".

<img width="772" alt="Screenshot 2020-05-15 at 16 19 33" src="https://user-images.githubusercontent.com/117428/82060631-eb62cb00-96c7-11ea-8711-72740d4037d6.png">

Direct link to the comment: https://github.com/sobstel/albicelestes/pull/19#commitcomment-39203163

**Comment by amondnet** [comment]
fixed https://github.com/amondnet/vercel-action/pull/3
