### ISSUE TITLE
Bump @actions/core to at least 1.2.6

### ISSUE THREAD

**Issue by paul-sachs** [amondnet/now-deployment#56]
This action now fails because of a security fix to github actions. Need to bump @actions/core in order to fix it.

![image](https://user-images.githubusercontent.com/11449728/99568456-6d94ba80-299d-11eb-94a8-ffeb825f712b.png)

**Comment by amondnet** [comment]
@paul-sachs Please use [this](https://github.com/amondnet/vercel-action) unless you have a specific reason. [This action](https://github.com/amondnet/vercel-action) fixed that issue.

**Comment by paul-sachs** [comment]
@amondnet yeah I dug around and found that after I made this. Thanks!
