### ISSUE TITLE
Built with commit undefined

### ISSUE THREAD

**Issue by foxundermoon** [amondnet/now-deployment#9]
after update pull-request

![image](https://user-images.githubusercontent.com/2764106/69956517-2a96c880-153b-11ea-9497-207711b8f630.png)

**Comment by amondnet** [comment]
https://github.com/amondnet/now-deployment/blob/e9d3e9f63c634480319cc5d367a7f3fdc1d2dddf/index.js#L38
@foxundermoon There seems to have been a change in github actions. The above code does not work.

**Comment by amondnet** [comment]
@foxundermoon fixed , thanks.
